version: "2"
linters:
  default: none
  enable:
    - dupl
    - dupword
    - err113
    - errcheck
    - errname
    - errorlint
    - godot
    - gosec
    - govet
    - ineffassign
    - nonamedreturns
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - usetesting
    - whitespace
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
