---
name: Go

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Essentially a hack: I want the tags. This feels a bit overkill though.
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13

    - name: Build
      run: make
